### ISSUE TITLE
Failed to component install littlstar/axis

### ISSUE THREAD

**Issue by dragonsoft-cara** [littlstar/axis#71]
When I do component install littlstar/axis
It ends up with error:

fs.js:932
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'D:\Cara\projects\useAxis\compo
nents\littlstar\axis\1.20.7.tar.gz'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at process.onexit (D:\Program Files\nodejs\node_modules\component\node_modul
es\component-downloader\lib\archive.js:87:8)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process.exit (node.js:750:17)
    at exports.fatal (D:\Program Files\nodejs\node_modules\component\node_module
s\component-consoler\index.js:73:11)
    at Resolver.<anonymous> (D:\Program Files\nodejs\node_modules\component\bin\
component-install:104:12)
    at Immediate._onImmediate (D:\Program Files\nodejs\node_modules\component\no
de_modules\co\index.js:52:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by jwerle** [comment]
axis is now built with babel/browserify
see the readme file for more details
